### ISSUE TITLE
Exception when call Server.Stop()

### ISSUE THREAD

**Issue by Tivaty** [mz-automation/lib60870.NET#26]
Hello,
I catch this exception all the time, when server has connection or no connection to client.
it is from the line of _listeningSocket.Shutdown(SocketShutdown.Both);_

the server is turned off but exception is still happen at this line.
Please support to check and update.
Thank you.

`System.Net.Sockets.SocketException
  HResult=0x80004005
  Message=A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.
  Source=System.Net.Sockets
  StackTrace:
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.Shutdown(SocketShutdown how)
   at lib60870.CS104.Server.Stop() in D:\work\C#\iec104\lib60870.NET\lib60870\CS104\Server.cs:line 943

  This exception was originally thrown at this call stack:
    [External Code]
    lib60870.CS104.Server.Stop() in Server.cs`

**Comment by juwiefer-btc** [comment]
This is another issue addressed in https://github.com/juwiefer-btc/lib60870.NET.

@mzillgith: You might want to skim through the diff to see the issues I have addressed. I could even create a pull request, but I guess my coding style might not fit in very well.
